include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - avoid_empty_else
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - annotate_redeclares
    - avoid_catching_errors
    - avoid_double_and_int_checks
    - avoid_dynamic_calls
    - avoid_escaping_inner_quotes
    - camel_case_types
    - cast_nullable_to_non_nullable
    - close_sinks
    - curly_braces_in_flow_control_structures
    - eol_at_end_of_file
    - exhaustive_cases
    - file_names
    - invalid_case_patterns
    - leading_newlines_in_multiline_strings
    - lines_longer_than_80_chars
    - only_throw_errors
    - prefer_asserts_in_initializer_lists
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_single_quotes
    - prefer_final_locals
    - prefer_foreach
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - require_trailing_commas
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_breaks
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_overrides
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_to_list_in_spreads
    - unnecessary_underscores
    - unrelated_type_equality_checks
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_named_constants
    - use_raw_strings
    - use_rethrow_when_possible
    - use_string_buffers
    - use_truncating_division
    - valid_regexps
    - void_checks
