// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type VerificationStatus string

const (
	VerificationStatusNoMatch         VerificationStatus = "no_match"
	VerificationStatusAlreadyVerified VerificationStatus = "already_verified"
	VerificationStatusJustVerified    VerificationStatus = "just_verified"
)

func (e *VerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationStatus(s)
	case string:
		*e = VerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationStatus: %T", src)
	}
	return nil
}

type NullVerificationStatus struct {
	VerificationStatus VerificationStatus
	Valid              bool // Valid is true if VerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationStatus), nil
}

type Email struct {
	UserID     string
	Email      string
	School     pgtype.Text
	CreatedAt  pgtype.Timestamptz
	VerifiedAt pgtype.Timestamptz
}

type MailList struct {
	Email     string
	CreatedAt pgtype.Timestamptz
}

type Post struct {
	Uri       string
	Cid       string
	AuthorDid string
	IndexedAt pgtype.Timestamptz
	Title     string
	Content   string
}

type Reaction struct {
	Uri       string
	PostUri   pgtype.Text
	AuthorDid string
	IndexedAt pgtype.Timestamptz
	Emote     string
}

type Reply struct {
	Uri        string
	Cid        string
	AuthorDid  string
	IndexedAt  pgtype.Timestamptz
	Title      string
	Content    string
	ReplyToUri string
}
