// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbutil

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	Uri            string
	Cid            string
	AuthorDid      string
	IndexedAt      pgtype.Timestamptz
	Title          string
	Content        string
	ReplyToPostCid pgtype.Text
}

type Reaction struct {
	Uri       string
	PostUri   pgtype.Text
	AuthorDid string
	IndexedAt pgtype.Timestamptz
	Emote     string
}
