// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	Uri       string
	Cid       string
	AuthorDid string
	IndexedAt pgtype.Timestamptz
	Title     string
	Content   string
}

type Reaction struct {
	Uri       string
	PostUri   pgtype.Text
	AuthorDid string
	IndexedAt pgtype.Timestamptz
	Emote     string
}

type Reply struct {
	Uri        string
	Cid        string
	AuthorDid  string
	IndexedAt  pgtype.Timestamptz
	Title      string
	Content    string
	ReplyToUri string
}
