name: "Determine Domain"
description: "Determines the domain for the deployment based on the current branch"
inputs:
  prod:
    description: "Production subdomain"
    required: true
  dev:
    description: "branch subdomain"
    required: true
outputs:
  domain:
    description: "Domain for the deployment"
    value: ${{ steps.determine.outputs.domain }}
runs:
  using: "composite"
  steps:
    - name: Determine Domain
      id: determine
      shell: bash
      run: |
        if [ "${{ inputs.dev }}" == "main" ]; then
          echo "domain=${{ inputs.prod }}" >> $GITHUB_OUTPUT
        else
          echo "domain=${{ inputs.dev }}-boshi" >> $GITHUB_OUTPUT
        fi
