apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourbillon
  labels:
    app: tourbillon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tourbillon
  template:
    metadata:
      labels:
        app: tourbillon
    spec:
      containers:
        - name: tourbillon
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          env:
            - name: FEEDGEN_PORT
              value: "${FEEDGEN_PORT}"
            - name: FEEDGEN_LISTENHOST
              value: "${FEEDGEN_LISTENHOST}"
            - name: FEEDGEN_POSTGRES_DATABASE
              value: "${FEEDGEN_POSTGRES_DATABASE}"
            - name: FEEDGEN_POSTGRES_USERNAME
              value: "${FEEDGEN_POSTGRES_USERNAME}"
            - name: FEEDGEN_POSTGRES_PASSWORD
              value: "${FEEDGEN_POSTGRES_PASSWORD}"
            - name: FEEDGEN_POSTGRES_HOST
              value: "${FEEDGEN_POSTGRES_HOST}"
            - name: FEEDGEN_POSTGRES_PORT
              value: "${FEEDGEN_POSTGRES_PORT}"
            - name: FEEDGEN_SUBSCRIPTION_ENDPOINT
              value: "${FEEDGEN_SUBSCRIPTION_ENDPOINT}"
            - name: FEEDGEN_HOSTNAME
              value: "${FEEDGEN_HOSTNAME}"
            - name: FEEDGEN_PUBLISHER_DID
              value: "${FEEDGEN_PUBLISHER_DID}"
            - name: FEEDGEN_SUBSCRIPTION_RECONNECT_DELAY
              value: "${FEEDGEN_SUBSCRIPTION_RECONNECT_DELAY}"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tourbillon
  labels:
    app: tourbillon
spec:
  selector:
    app: tourbillon
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tourbillon-ingress
  annotations:
    cert-manager.io/cluster-issuer: ${CLUSTER_ISSUER}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${DOMAIN}
      secretName: tourbillon-tls
  rules:
    - host: ${DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tourbillon
                port:
                  number: 80
