name: "Create/Update K8s Deployment"
description: "Creates or Updates a K8s Deployment on the SSH host"
inputs:
  host:
    description: "SSH Host"
    required: true
  username:
    description: "SSH Username"
    required: true
  key:
    description: "SSH Key"
    required: true
  port:
    description: "SSH Port"
    required: true
  config-path:
    description: "Path to the config"
    required: true
  docker-image:
    description: "Docker image"
    required: true
  namespace:
    description: "Kubernetes namespace"
    required: true
  update-deployment:
    description: "Update the deployment if it exists"
    required: false
    default: "true"
  config-envs:
    description: "Additional environment variables for the K8s config"
    required: false
  domain:
    description: "Domain of the deployment"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Create Deployment
      uses: appleboy/ssh-action@v1.2.0
      env:
        DOMAIN: ${{ inputs.domain }}
        CONFIG_PATH: ${{ inputs.config-path }}
        IMAGE: ${{ inputs.docker-image }}
        NAMESPACE: ${{ inputs.namespace }}
        UPDATE_DEPLOYMENT: ${{ inputs.update-deployment }}
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        port: ${{ inputs.port }}
        envs: NAMESPACE,CONFIG_PATH,IMAGE,DOMAIN,UPDATE_DEPLOYMENT,${{inputs.config-envs}}
        script: |
          if ! kubectl get namespace "$NAMESPACE" > /dev/null 2>&1; then
            echo "Creating namespace $NAMESPACE and deploying"
            kubectl create namespace "$NAMESPACE"
            envsubst < ${CONFIG_PATH} \
              | kubectl apply -f - -n "$NAMESPACE"
          elif [[ "${UPDATE_DEPLOYMENT}" == "true" ]]; then
            echo "Updating deployment"
            envsubst < ${CONFIG_PATH} \
              | kubectl apply -f - -n "$NAMESPACE"
          fi
