name: Branch Deleted
on: delete
jobs:
  build-info:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-info
  delete:
    needs: [build-info]
    name: Delete Deployment Resources
    runs-on: ubuntu-latest
    steps:
      - name: Delete Deployment
        uses: appleboy/ssh-action@v1.2.0
        env:
          NAMESPACE: ${{needs.build-info.outputs.namespace}}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: NAMESPACE
          script: |
            if kubectl get namespace $NAMESPACE >/dev/null 2>&1; then
              kubectl delete namespace $NAMESPACE
            else
              echo "Namespace '$NAMESPACE' not found. Not deleting anything."
            fi
