name: Pull Request Push
on:
  pull_request:
    branches-ignore:
      - dev
      - main
    types: [synchronize]
jobs:
  convert-branch-name:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.convert.outputs.name }}
    steps:
      - id: convert
        env:
            BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          output=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed -E 's/^-+|-+$//g')
          echo "$output" >> $GITHUB_ENV
  # build:
  #   runs-on: ubuntu-latest
  #   needs: convert-branch-name
  #   env:
  #       BRANCH_NAME: ${{needs.convert-branch-name.outputs.name}}
  #   steps:
  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ vars.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
  #   - name: Build image
  #     run: make docker
  #   - name: Push image with commit sha
  #     run: make docker-push TAG=$BRANCH_NAME-$(git rev-parse --short "$GITHUB_SHA")
  #   - name: Push image with latest tag
  #     run: make docker-push TAG=$BRANCH_NAME-latest
  # deploy:
  #   needs: [build, convert-branch-name]
  #   name: Create Deployment
  #   runs-on: ubuntu-latest
  #   env:
  #       BRANCH_NAME: ${{needs.convert-branch-name.outputs.name}}
  #   steps:
  #     - name: Rollout deployment
  #       uses: appleboy/ssh-action@v1.2.0
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         key: ${{ secrets.SSH_KEY }}
  #         port: ${{ secrets.SSH_PORT }}
  #         script: |
  #           kubectl rollout restart deployment boshi-backend -n boshi-$BRANCH_NAME
  #
