name: Branch Push
on: push
jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          backend:
            - 'backend/go.mod'
            - 'backend/cmd/**'
            - 'backend/internal/**'
            - 'backend/.dockerignore'
            - 'backend/Dockerfile'
            - 'backend/scripts/**'
            - 'backend/configs/**'
            - '.github/workflows/push.yaml'

  convert-branch-name:
    needs: changes
    name: Convert Branch Name
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.backend == 'true' }}
    outputs:
      name: ${{ steps.convert.outputs.name }}
    steps:
      - id: convert
        env:
            BRANCH_NAME: "${{ github.head_ref || github.ref_name }}"
        run: |
          output=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed -E 's/^-+|-+$//g')
          echo "name=$output" >> $GITHUB_OUTPUT
  build-backend:
    needs: convert-branch-name
    name: Build Backend
    runs-on: ubuntu-latest
    if : ${{ needs.changes.outputs.backend == 'true' }}
    env:
        BRANCH_NAME: ${{needs.convert-branch-name.outputs.name}}
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build image
      run: cd backend && make docker
    - name: Push image with commit sha
      run: cd backend && make docker-push TAG=$BRANCH_NAME-$(git rev-parse --short "$GITHUB_SHA")
    - name: Push image with latest tag
      run: >-
        if [[ $BRANCH_NAME == "main" ]]; then
          cd backend && make docker-push TAG=latest
        else
          cd backend && make docker-push TAG=$BRANCH_NAME-latest
        fi
  deploy-backend:
    needs: [build-backend, convert-branch-name]
    name: Create Backend Deployment
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{needs.convert-branch-name.outputs.name}}
      REGISTRY: ${{ vars.DOCKER_REGISTRY }}
    steps:
      - name: Create/Update Deployment
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: BRANCH_NAME,REGISTRY
          script: |
            if [[ $BRANCH_NAME == "main" ]]; then
              export NAMESPACE="boshi";
            else
              export NAMESPACE="boshi-$BRANCH_NAME";
            fi

            if kubectl get namespace $NAMESPACE >/dev/null 2>&1; then
              kubectl rollout restart deployment boshi-backend -n $NAMESPACE
            else
              kubectl create namespace $NAMESPACE
              kubectl create deployment boshi-backend --image=$REGISTRY/boshi-backend:$BRANCH_NAME-latest --port=80 -n $NAMESPACE
              kubectl expose deployment boshi-backend --name=boshi-backend-svc --port=80 --target-port=80 --type=ClusterIP -n $NAMESPACE
              kubectl create ingress ingress --annotation cert-manager.io/cluster-issuer="letsencrypt-prod" --class=nginx --rule="$BRANCH_NAME-boshi.deguzman.cloud/api/*=boshi-backend-svc:80,tls=boshi-tls" --rule="$BRANCH_NAME-boshi.deguzman.cloud/oauth/*=boshi-backend-svc:80,tls=boshi-tls" -n $NAMESPACE
            fi
